CREATE SCHEMA IF NOT EXISTS relacional_v1;

-- 1. TABLAS MAESTRAS

CREATE TABLE IF NOT EXISTS relacional_v1.Edificio (
  id_edificio INT GENERATED BY DEFAULT AS IDENTITY,
  nombre VARCHAR(50) NOT NULL,
  ubicacion VARCHAR(100) NOT NULL,
  capacidad_habitaciones INT NOT NULL,
  genero VARCHAR(10) NOT NULL,
  PRIMARY KEY (id_edificio),
  CONSTRAINT chk_genero_edificio CHECK (genero IN ('Masculino', 'Femenino'))
);

CREATE TABLE IF NOT EXISTS relacional_v1.Usuario (
  id_usuario INT GENERATED BY DEFAULT AS IDENTITY,
  nombre VARCHAR(50) NOT NULL,
  rut VARCHAR(20) NOT NULL,
  contrasena VARCHAR(100) NOT NULL,
  tipo_usuario VARCHAR(15) NOT NULL,
  PRIMARY KEY (id_usuario),
  UNIQUE (rut),
  CONSTRAINT chk_tipo_usuario CHECK (tipo_usuario IN ('Admin', 'Estudiante'))
);

CREATE TABLE IF NOT EXISTS relacional_v1.Periodo (
  id_periodo INT GENERATED BY DEFAULT AS IDENTITY,
  nombre VARCHAR(50) NOT NULL,
  fecha_inicio DATE NOT NULL,
  fecha_termino DATE NOT NULL,
  PRIMARY KEY (id_periodo)
);

-- 2. INFRAESTRUCTURA

CREATE TABLE IF NOT EXISTS relacional_v1.Piso (
  id_piso INT GENERATED BY DEFAULT AS IDENTITY,
  nro_piso INT NOT NULL,
  nombre VARCHAR(20) NOT NULL,
  id_edificio INT NOT NULL,
  PRIMARY KEY (id_piso),
  FOREIGN KEY (id_edificio) REFERENCES relacional_v1.Edificio (id_edificio)
);

CREATE TABLE IF NOT EXISTS relacional_v1.Habitacion (
  id_habitacion INT GENERATED BY DEFAULT AS IDENTITY,
  disponibilidad BOOLEAN NOT NULL,
  capacidad_actual INT NOT NULL,
  nro_habitacion INT NOT NULL,
  id_piso INT NOT NULL,
  PRIMARY KEY (id_habitacion),
  FOREIGN KEY (id_piso) REFERENCES relacional_v1.Piso (id_piso)
);

-- 3. GESTION Y ASIGNACIONES

CREATE TABLE IF NOT EXISTS relacional_v1.Plan_alimenticio (
  id_plan INT GENERATED BY DEFAULT AS IDENTITY,
  tipo_plan VARCHAR(30) NOT NULL,
  id_periodo INT NOT NULL,
  id_usuario INT NOT NULL,
  PRIMARY KEY (id_plan),
  FOREIGN KEY (id_periodo) REFERENCES relacional_v1.Periodo (id_periodo),
  FOREIGN KEY (id_usuario) REFERENCES relacional_v1.Usuario (id_usuario),
  CONSTRAINT chk_plan_alimento CHECK (
    tipo_plan IN ('Sin preferencia', 'Vegetariano', 'Vegano', 'Pescetariano')
  )
);

CREATE TABLE IF NOT EXISTS relacional_v1.Asignacion_estancia (
  id_asignacion INT GENERATED BY DEFAULT AS IDENTITY,
  fecha_asignacion DATE NOT NULL,
  fecha_check_in DATE NULL,
  fecha_check_out DATE NULL,
  estado VARCHAR(20) NOT NULL,
  id_habitacion INT NOT NULL,
  id_periodo INT NOT NULL,
  id_usuario INT NOT NULL,
  PRIMARY KEY (id_asignacion),
  FOREIGN KEY (id_habitacion) REFERENCES relacional_v1.Habitacion (id_habitacion),
  FOREIGN KEY (id_periodo) REFERENCES relacional_v1.Periodo (id_periodo),
  FOREIGN KEY (id_usuario) REFERENCES relacional_v1.Usuario (id_usuario),
  CONSTRAINT chk_estado_estancia CHECK (
    estado IN ('Activa', 'Finalizada', 'Renunciada')
  )
);

CREATE TABLE IF NOT EXISTS relacional_v1.Solicitudes (
  id_solicitud INT GENERATED BY DEFAULT AS IDENTITY,
  estado VARCHAR(20) NOT NULL,
  fecha_solicitud DATE NOT NULL,
  id_periodo INT NOT NULL,
  id_asignacion INT NULL,
  id_usuario INT NOT NULL,
  PRIMARY KEY (id_solicitud),
  FOREIGN KEY (id_periodo) REFERENCES relacional_v1.Periodo (id_periodo),
  FOREIGN KEY (id_asignacion) REFERENCES relacional_v1.Asignacion_estancia (id_asignacion),
  FOREIGN KEY (id_usuario) REFERENCES relacional_v1.Usuario (id_usuario),
  CONSTRAINT chk_estado_solicitud CHECK (
    estado IN ('En Revision', 'Aprobada', 'Rechazada', 'Pendiente')
  )
);

CREATE TABLE IF NOT EXISTS relacional_v1.Incidencia_estancia (
  id_incidencia INT GENERATED BY DEFAULT AS IDENTITY,
  descripcion VARCHAR(500) NOT NULL,
  estado VARCHAR(20) NOT NULL,
  fecha DATE NOT NULL,
  gravedad VARCHAR(20) NOT NULL,
  id_habitacion INT NOT NULL,
  id_usuario INT NOT NULL,
  PRIMARY KEY (id_incidencia),
  FOREIGN KEY (id_habitacion) REFERENCES relacional_v1.Habitacion (id_habitacion),
  FOREIGN KEY (id_usuario) REFERENCES relacional_v1.Usuario (id_usuario),
  CONSTRAINT chk_estado_incidencia CHECK (
    estado IN ('Pendiente', 'En Proceso', 'Resuelta')
  ),
  CONSTRAINT chk_gravedad_incidencia CHECK (
    gravedad IN ('Leve', 'Moderado', 'Grave')
  )
);
